### ISSUE TITLE
Keyboard Navigation

### ISSUE THREAD

**Issue by brightOrigin** [nickvdp/RecentTabList#1]
Hi,

Great extension! I am a recent Chrome convert and came across your extension while trying to replicate my old setup.

Are there any plans to make the extension more keyboard friendly? My two top requests are:
- Keyboard shortcut to trigger the popup
- Keyboard navigation within the list - be able to use the up/down arrows to navigate the list as well as Return to select a tab in the list.

Thanks

**Comment by worthbak** [comment]
Same idea here! This extension would be 100x more useful if I could navigate via the keyboard. 

Thanks for making something awesome!

**Comment by nickvdp** [comment]
Thanks for the comments! I'll look into keyboard shortcuts soon.

**Comment by ant8e** [comment]
Great extension, Keyboard navigation would make it awesome

**Comment by nickvdp** [comment]
Unfortunately, it isn't possible to assign a hot key to open an extension popover in Safari. 

You can get around this by injecting Javascript into each page to capture keystrokes and open the popup. However, it only works when the page is the focus, so it won't work on a blank tab, the new tab page, while a page is loading, or when a menu/toolbar/URL is selected.

So, I'm not willing to add it since it won't work ~20% of the time and will just seem broken and frustrating to most users.

This post (by another Safari extension developer) goes over it pretty well: http://code.antrikshy.com/safari-extension-development-keyboard-shortcuts/

I'm going to look into keyboard nav within the list, though I imagine it's a lot less useful if you need the mouse to open the list in the first place.

**Comment by gingerbeardman** [comment]
Here's my solution to the hotkey problem, which uses Alfred to capture the Hotkey and AppleScript to click the Toolbar Button.

https://github.com/nickvdp/RecentTabList/issues/13#issuecomment-395111542
